---
apiVersion: v1
kind: Namespace
metadata:
  name: pictive-minimal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pictive
  namespace: pictive-minimal
spec:
  selector:
    matchLabels:
      app: pictive-platform
  template:
    metadata:
      labels:
        app: pictive-platform
    spec:
      containers:
      - name: pictive
        # v0.0.2-SNAPSHOT
        image: "antsinmyey3sjohnson/pictive-platform-mvp@sha256:da60d9f7a79f466a83c9d24a7470b0cc6beec51824f3ef60a3e81afb4c786187"
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: local
        - name: SPRING_CLOUD_GCP_VISION_ENABLED
          value: "false"
        - name: SPRING_CLOUD_GCP_CORE_ENABLED
          value: "false"
        resources:
          requests:
            cpu: 200m
            memory: 320Mi
          limits: 
            cpu: 200m
            memory: 320Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pictive
  namespace: pictive-minimal
spec:
  selector:
    app: pictive-platform
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: http

    