---
apiVersion: v1
kind: Namespace
metadata:
  name: pictive-minimal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pictive
  namespace: pictive-minimal
spec:
  selector:
    matchLabels:
      app: pictive-platform
  template:
    metadata:
      labels:
        app: pictive-platform
    spec:
      containers:
      - name: pictive
        # v0.0.4-SNAPSHOT
        image: "antsinmyey3sjohnson/pictive-platform-mvp@sha256:c67842730de9bbbf4dfa0fafa6d793f144735cd79f76209f2b73874fb4e397c5"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: local
        - name: SPRING_CLOUD_GCP_VISION_ENABLED
          value: "false"
        - name: SPRING_CLOUD_GCP_CORE_ENABLED
          value: "false"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits: 
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pictive
  namespace: pictive-minimal
spec:
  selector:
    app: pictive-platform
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30080
    targetPort: http

    
