---
apiVersion: v1
kind: Namespace
metadata:
  name: pictive-minimal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pictive
  namespace: pictive-minimal
spec:
  selector:
    matchLabels:
      app: pictive-platform
  template:
    metadata:
      labels:
        app: pictive-platform
    spec:
      containers:
      - name: pictive
        # v0.0.5-SNAPSHOT
        image: "antsinmyey3sjohnson/pictive-platform-mvp@sha256:41370ae0065f6e87a2de9b0ac33e97d3184009d78335ccae12a97481f60499ae"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 30
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 30
          initialDelaySeconds: 60
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: local
        - name: SPRING_CLOUD_GCP_VISION_ENABLED
          value: "false"
        - name: SPRING_CLOUD_GCP_CORE_ENABLED
          value: "false"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits: 
            cpu: 1
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pictive
  namespace: pictive-minimal
spec:
  selector:
    app: pictive-platform
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30080
    targetPort: http

    
