---
apiVersion: v1
kind: Namespace
metadata:
  name: pictive-minimal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pictive
  namespace: pictive-minimal
spec:
  selector:
    matchLabels:
      app: pictive-platform
  template:
    metadata:
      labels:
        app: pictive-platform
    spec:
      containers:
      - name: pictive
        image: "antsinmyey3sjohnson/pictive-platform-mvp@sha256:2b76eb234e5a765c0161246a1116a2a873bf6dba7bb1a9ee26da5c5bc5228f0b"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits: 
            cpu: 200m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pictive
  namespace: pictive-minimal
spec:
  selector:
    app: pictive-platform
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: http

    