---
apiVersion: v1
kind: Namespace
metadata:
  name: pictive-minimal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pictive
  namespace: pictive-minimal
spec:
  selector:
    matchLabels:
      app: pictive-platform
  template:
    metadata:
      labels:
        app: pictive-platform
    spec:
      containers:
      - name: pictive
        image: "antsinmyey3sjohnson/pictive-platform-mvp:0.0.1-SNAPSHOT"
        env:
        - name: JAVA_OPTS
          value: "-Xmx256m -Xms256m" 
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits: 
            cpu: 200m
            memory: 300Mi
    